;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="GameplayCue.PlayerMuzzleFlash",NewTagName="GameplayCue.PlayerBasicMuzzleFlash")
+GameplayTagRedirects=(OldTagName="Custom.Player.BulletHit\\",NewTagName="Custom.Player.BulletHit")
+GameplayTagRedirects=(OldTagName="GameplayCue.PlayerBasicBullet",NewTagName="GameplayCue.PlayerDefaultBullet")
+GameplayTagRedirects=(OldTagName="GameplayCue.PlayerBasicMuzzleFlash",NewTagName="GameplayCue.PlayerDefaultMuzzleFlash")
+GameplayTagRedirects=(OldTagName="GameplayCue.PlayerDefaultBullet",NewTagName="GameplayCue.PlayerDefaultBulletHit")
+GameplayTagRedirects=(OldTagName="GameplayCue.ElectricBulletHit",NewTagName="GameplayCue.PlayerElectricBulletHit")
+GameplayTagRedirects=(OldTagName="GameplayCue.ElectricMuzzleFlash",NewTagName="GameplayCue.PlayerElectricMuzzleFlash")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Custom",DevComment="")
+GameplayTagList=(Tag="Custom.Cooldown.Rolling",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.Burn",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.BurnDuration",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.ConsumeAmmo",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.Cooldown",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.Reload",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.Stun",DevComment="")
+GameplayTagList=(Tag="Custom.Effect.StunDuration",DevComment="")
+GameplayTagList=(Tag="Custom.Hit",DevComment="")
+GameplayTagList=(Tag="Custom.Player",DevComment="")
+GameplayTagList=(Tag="Custom.Player.BulletHit",DevComment="")
+GameplayTagList=(Tag="Custom.Player.Fire",DevComment="")
+GameplayTagList=(Tag="Custom.Player.Skill.Rolling",DevComment="")
+GameplayTagList=(Tag="Custom.State.Stun",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Burning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PlayerDefaultBulletHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PlayerDefaultMuzzleFlash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PlayerElectricBulletHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PlayerElectricMuzzleFlash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.PlayerReload",DevComment="")

